name: "Build GAP package"
description: "Builds the GAP package being tested"
inputs:
  COVERAGE:
    description: "Set to true to gather coverage"
    required: false
    default: false
  CONFIGFLAGS:
    description: "Additional arguments to be passed to configure"
    required: false
    default: ""

runs:
  using: "composite"
  steps:
  
    - name: "Build the package"
      shell: bash
      run: |
        set -ex
        
        # Ensure coverage is turned on
        if [ "${{ inputs.COVERAGE }}" == "true" ]; then
            export CFLAGS="$CFLAGS --coverage"
            export CXXFLAGS="$CXXFLAGS --coverage"
            export LDFLAGS="$LDFLAGS --coverage"
        fi
        
        # Build this package, if necessary
        if [[ -x prerequisites.sh ]]; then
            ./prerequisites.sh $GAP_HOME
        fi
        if [[ -x autogen.sh ]]; then
            ./autogen.sh
        fi
        if grep Autoconf ./configure > /dev/null
        then
            ./configure --with-gaproot=$GAP_HOME ${{ inputs.CONFIGFLAGS }}
            make -j4 V=1
        elif [[ -x configure ]]; then
            ./configure ${{ inputs.CONFIGFLAGS }} $GAP_HOME
            make -j4 CFLAGS="$CFLAGS" CXXFLAGS="$CXXFLAGS" LDFLAGS="$LDFLAGS"
        fi
